admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

hello_the_world:
    path:       /hello-world
    controller: LFDPP\AdminBundle\Controller\FrontController::index
