services:
#    admin.example:
#        class: LFDPP\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    
     admin.validator_form:
        class: LFDPP\AdminBundle\Service\ValidatorForm
        public: true
