<?php

namespace LFDPP\AdminBundle\Repository;

/**
 * MessageTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
