<?php

namespace LFDPP\AdminBundle\Repository;

/**
 * PagesTexteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesTexteRepository extends \Doctrine\ORM\EntityRepository
{
}
