<?php

namespace LFDPP\AdminBundle\Repository;

/**
 * PriceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
